//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TileMapEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_PASTE_MENU                  101
#define IDR_WINDOWS_MENU                102
#define IDS_RIBBON_FILE                 103
#define IDS_RIBBON_NEW                  104
#define IDS_RIBBON_OPEN                 105
#define IDS_RIBBON_SAVE                 106
#define IDS_RIBBON_SAVEAS               107
#define IDS_RIBBON_PRINT                108
#define IDS_RIBBON_PRINT_LABEL          109
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDS_RIBBON_PRINT_QUICK          116
#define IDS_RIBBON_PRINT_PREVIEW        117
#define IDS_RIBBON_PRINT_SETUP          118
#define IDR_POPUP_EDIT                  119
#define IDS_RIBBON_CLOSE                120
#define IDS_RIBBON_RECENT_DOCS          121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_RIBBON_EXIT                 124
#define IDS_RIBBON_HOME                 125
#define IDS_RIBBON_CLIPBOARD            126
#define IDS_RIBBON_PASTE                127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_TileMapEditorTYPE           130
#define IDS_RIBBON_CUT                  131
#define IDS_WINDOWS_MANAGER             132
#define IDS_RIBBON_COPY                 133
#define IDS_RIBBON_SELECTALL            134
#define IDS_RIBBON_WINDOW               135
#define IDS_RIBBON_WINDOWS              136
#define IDS_RIBBON_STYLE                137
#define IDS_RIBBON_STYLE_TIP            138
#define IDS_RIBBON_STYLE_DESC           139
#define IDS_RIBBON_STATUSBAR            140
#define IDS_RIBBON_VIEW                 141
#define IDS_OUTPUT_LOG_TAB              142
#define IDS_DEBUG_TAB                   143
#define IDS_FIND_TAB                    144
#define IDS_EXPLORER                    145
#define IDS_EDIT_MENU                   146
#define IDS_RES_DETAIL                  147
#define IDS_MAPLAYER_PANEL              148
#define IDS_RES_PANEL                   149
#define IDS_MAP_PANEL                   150
#define IDS_OUTPUT_WND                  151
#define IDS_PROPERTIES_WND              152
#define IDI_FILE_VIEW                   153
#define IDI_FILE_VIEW_HC                154
#define IDI_CLASS_VIEW                  155
#define IDI_CLASS_VIEW_HC               156
#define IDI_OUTPUT_WND                  157
#define IDI_OUTPUT_WND_HC               158
#define IDI_PROPERTIES_WND              159
#define IDI_PROPERTIES_WND_HC           160
#define IDR_EXPLORER                    161
#define IDB_EXPLORER_24                 162
#define IDR_SORT                        163
#define IDB_SORT_24                     164
#define IDR_POPUP_SORT                  165
#define IDR_POPUP_EXPLORER              166
#define IDB_FILE_VIEW                   167
#define IDB_FILE_VIEW_24                168
#define IDB_CLASS_VIEW                  169
#define IDB_CLASS_VIEW_24               170
#define IDR_MENU_IMAGES                 171
#define IDB_MENU_IMAGES_24              172
#define IDR_OUTPUT_POPUP                173
#define IDR_PROPERTIES                  174
#define IDB_PROPERTIES_HC               175
#define IDR_THEME_MENU                  176
#define IDD_DIALOG_FILE_NEW             177
#define IDR_MENU_LAYER_OP               178
#define IDR_MENU_BRUSH_OP               179
#define IDR_MENU_MAPLAYER_OP            180
#define IDD_DIALOG_NEWLAYER             181
#define IDS_MAP_THUMBNAIL               182
#define IDI_MAPLAYER                    183
#define IDI_MAPLAYER_HC                 184
#define IDR_TOOLBAR_GOEDITOR            185
#define IDS_GAMEOBJECT_EDITOR           186
#define IDD_DIALOG_GO_EDITOR            187
#define IDR_TOOLBAR_RESDETAIL           188
#define IDR_MENU_MAPBRUSH_OP            189
#define IDR_TOOLBAR_MAPLAYER            190
#define IDD_DIALOG_RES_DETAIL           191
#define IDR_MENU_POPUP_RESVIEW          192
#define IDR_MENU_GAMEOBJECTGROUP        193
#define IDD_DIALOG_ADD_GAMEOBJECTGRPUP  194
#define IDR_MENU_POPUP_GAMEOBJECT_ADD   195
#define M_TOOL_SELECT                   196
#define M_TOOL_BRUSH                    197
#define M_TOOL_REGION                   198
#define M_TOGGLE_FULL_SCREEN            199
#define IDR_MENU_RESOURCE_TILE          200
#define IDD_DIALOG_ADD_RESOUECE_TILE    203
#define M_TOOL_COMBO_REGION             204
#define M_TOOL_EXPORT_MAP               205
#define M_TOOL_RESOURCE_STAT            206
#define IDC_EDIT_WIDTH                  1000
#define IDC_EDIT_HEIGHT                 1001
#define IDC_EDIT_FOOTNOTES              1002
#define IDC_EDIT_REGION_WIDTH           1003
#define IDC_EDIT_MAPNAME                1004
#define IDC_EDIT_TILE_SIZE              1005
#define IDC_EDIT_TILE_HEIGHT            1006
#define IDC_EDIT_LAYERNAME              1007
#define IDC_EDIT_TILE_WIDTH             1008
#define IDC_EDIT_BUILDIN_LAYER_H        1009
#define IDC_EDIT_GO_ARTGROUP            1010
#define IDC_EDIT_REGION_HEIGHT          1011
#define IDC_CHECK_CREATE_LAYER          1012
#define IDC_EDIT_GO_GROUP               1013
#define IDC_EDIT_GO_OBJ_NAME            1014
#define IDC_EDIT_GO_TILEH               1015
#define IDC_EDIT_GO_TILEW               1016
#define IDC_EDIT_GO_TILE_COUNT_X        1017
#define IDC_EDIT_GO_TILE_COUNT_Y        1018
#define IDC_EDIT_AITYPE                 1018
#define IDC_EDIT_GO_CENTER_POS          1019
#define IDC_BUTTON_GO_CUR_BRUSH         1020
#define IDC_COMBO_TYPE                  1021
#define IDC_RADIO_GO_SELECT             1022
#define IDC_RADIO_GO_SET_OBSTACLE       1023
#define IDC_COMBO_GO_ARTID              1024
#define IDC_COMBO_GO_AI                 1025
#define IDC_RADIO_GO_CLEAR_OBSTACLE     1026
#define IDC_EDIT_GO_MAPTYPE             1027
#define IDC_EDIT_RES_DETAIL_GROUPNAME   1028
#define IDC_EDIT_TILEW                  1029
#define IDC_EDIT_TILEH                  1030
#define IDC_COMBO_ARTRES                1031
#define IDC_EDIT_RES_DETAIL_RESTYPE     1032
#define IDC_BUTTON_GO_OK                1033
#define IDC_RADIO_MAPTYPE               1034
#define IDC_RADIO_MAPTYPE2              1035
#define IDC_EDIT_RES_DETAIL_GROUPNAME2  1036
#define IDC_RADIO_TILE_TYPE2            1037
#define IDC_BUTTON_GO_CANCEL            1038
#define IDC_BUTTON_BROWSE               1039
#define IDC_STATIC_NAME                 1040
#define IDC_EDIT_TILE_NAME              1041
#define IDC_COMBO_ICONSIZE              1042
#define IDC_EDIT_EXT                    1043
#define IDC_STATIC_TILE_SIZE            1044
#define IDC_EDIT_TILE_SIZE_W            1045
#define IDC_EDIT_TILE_SIZE_H            1046
#define IDC_EDIT_COUNT                  1047
#define IDC_STATIC_EXT                  1048
#define IDC_STATIC_COUNT                1049
#define IDC_STATIC_PIXEL_W              1050
#define IDC_EDIT_RES_GRIDTYPE           1051
#define IDC_STATIC_PIXEL_RW             1052
#define IDC_STATIC_PIXEL_RH             1053
#define IDC_EDIT_GROUPNAME              1054
#define IDC_EDIT_RES_GRIDSIZE           1055
#define IDC_SPIN                        1056
#define IDC_RADIO_TILE_TYPE             1057
#define IDC_EDIT1                       1058
#define IDC_EDIT_RES_NAME               1059
#define IDC_STATIC_PIXEL_H              1060
#define IDC_CHECK_LAYER_BACKGROUND      1061
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_STATUSBAR_PANE1              32771
#define ID_STATUSBAR_PANE2              32772
#define ID_WINDOW_MANAGER               32773
#define ID_VIEW_RES_PANEL               32774
#define ID_VIEW_MAP_PANEL               32775
#define ID_PROPERTIES                   32776
#define ID_OPEN                         32777
#define ID_OPEN_WITH                    32778
#define ID_DUMMY_COMPILE                32779
#define ID_CLASS_ADD_MEMBER_FUNCTION    32780
#define ID_CLASS_ADD_MEMBER_VARIABLE    32781
#define ID_CLASS_DEFINITION             32782
#define ID_CLASS_PROPERTIES             32783
#define ID_NEW_FOLDER                   32784
#define ID_SORT_MENU                    32785
#define ID_SORTING_GROUPBYTYPE          32786
#define ID_SORTING_SORTALPHABETIC       32787
#define ID_SORTING_SORTBYTYPE           32788
#define ID_SORTING_SORTBYACCESS         32789
#define ID_VIEW_OUTPUTWND               32790
#define ID_VIEW_PROPERTIESWND           32791
#define ID_VIEW_RES_DETAIL_PANEL        32792
#define ID_SORTPROPERTIES               32793
#define ID_VIEW_MAPLAYER_PANEL          32794
#define ID_PROPERTIES1                  32795
#define ID_PROPERTIES2                  32796
#define ID_EXPAND_ALL                   32797
#define ID_TOOLS_MACRO                  32798
#define ID_SET_STYLE                    32799
#define ID_VIEW_APPLOOK_WIN_2000        32800
#define ID_VIEW_APPLOOK_OFF_XP          32801
#define ID_VIEW_APPLOOK_WIN_XP          32802
#define ID_VIEW_APPLOOK_OFF_2003        32803
#define ID_VIEW_APPLOOK_VS_2005         32804
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   32805
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  32806
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 32807
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   32808
#define ID_LAYEROP_SHOW                 32809
#define ID_LAYEROP_HIDE                 32810
#define ID_LAYEROP_REMOVE               32811
#define ID_LAYEROP_SETCURRENT           32812
#define ID_LAYEROP_INSERT               32813
#define ID_BRUSHOP_ADDBRUSH             32814
#define ID_BRUSHOP_REMOVEBRUSH          32815
#define ID_BRUSHOP_SELECTBRUSH          32816
#define ID_MAPOP_DEFINEBRUSH            32817
#define ID_VIEW_GAMEOBJECTEDITOR        32818
#define ID_TOOLBAR_MAPLAYER_SELECT_SIMILAR 32819
#define ID_TOOLBAR_MAPLAYER_INVERT_SELECT 32820
#define ID_TOOLBAR_MAPLAYER_DELETE_SELECT 32821
#define ID_RESVIEW_REMOVE               32822
#define ID_RESVIEW_ADD                  32823
#define ID_RESVIEW_EDIT                 32824
#define ID_MENU_RESVIEW_ADD             32825
#define ID_MENU_RESVIEW_EDIT            32826
#define ID_MENU_RESVIEW_REMOVE          32827
#define ID_GAMEOBJECTGROUP_ADDGROUP     32828
#define ID_GAMEOBJECTGROUP_REMOVEGROUP  32829
#define ID_VIEW_MAP_THUMBNAIL_PANEL     32830
#define ID_LAYEROP_MOVE_DOWN            32831
#define ID_LAYEROP_MOVE_UP              32832
#define ID_LAYEROP_MOVE_BOTTOM          32833
#define ID_LAYEROP_MOVE_TOP             32834
#define ID_RESOURCE_TILE_ADD            32835
#define ID_RESOURCE_TILE_REMOVE         32836
#define ID_RESVIEW_32837                32837
#define ID_MENU_RESVIEW_COPY            32838
#define ID_BUTTON32839                  32839
#define ID_TOOLBAR_MAPLAYER_EXPORT      32839

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        207
#define _APS_NEXT_COMMAND_VALUE         32840
#define _APS_NEXT_CONTROL_VALUE         1062
#define _APS_NEXT_SYMED_VALUE           1162
#endif
#endif
